project:
  type: website
  output-dir: docs

website:
  title: "Liripo"
  site-url: https://liripo.github.io
  description: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Liripo
      - icon: twitter
        href: https://twitter.com/Liripo_zzz
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: true

